package main

import (
	"fmt"
	"net/http"

	"transit-api/handler"

	_ "transit-api/docs" // docs are generated by Swag CLI, you have to import it.

	"github.com/jtclarkjr/router-go"
	"github.com/jtclarkjr/router-go/middleware"
	httpSwagger "github.com/swaggo/http-swagger/v2"
)

// @title Transit API JP
// @version 1.0
// @description API for Japanese transit route planning and station autocomplete
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.url http://www.swagger.io/support
// @contact.email support@example.com

// @license.name MIT
// @license.url https://opensource.org/licenses/MIT

// @host localhost:8080
// @BasePath /

func main() {
	r := router.NewRouter()

	// CORS middleware to allow all origins
	r.Use(middleware.SimpleCORS())

	r.Use(middleware.EnvVarChecker("RAPIDAPI_KEY", "RAPIDAPI_TRANSPORT_HOST", "RAPIDAPI_TRANSIT_HOST", "OPENAI_API_KEY"))

	// Throttling for all API routes
	// Throttle: limits concurrent in-flight requests to 1000
	// Note: Rate limiting is now applied per API call (not per request) in handlers
	// Cached responses bypass rate limiting entirely
	r.Use(middleware.Throttle(1000))
	r.Use(middleware.LoggerWithConfig(middleware.LoggerConfig{
		IncludeTimestamp: false,
	}))

	// Add a basic root route for testing
	r.Get("/", func(w http.ResponseWriter, r *http.Request) {
		if _, err := w.Write([]byte("Transit API JP - Server is running")); err != nil {
			http.Error(w, "Internal Server Error", http.StatusInternalServerError)
		}
	})
	// Swagger UI - using wildcard pattern
	r.Get("/swagger/*", httpSwagger.WrapHandler)
	// Handle Swagger assets that are requested without /swagger/ prefix
	r.Get("/swagger-ui.css", httpSwagger.WrapHandler)
	r.Get("/swagger-ui-bundle.js", httpSwagger.WrapHandler)
	r.Get("/swagger-ui-standalone-preset.js", httpSwagger.WrapHandler)
	r.Get("/transit", handler.Transit())
	r.Get("/autocomplete", handler.Autocomplete)
	r.Post("/transit-agent", handler.TransitAgent)

	fmt.Println("Starting server on :8080")
	err := http.ListenAndServe(":8080", r)
	if err != nil {
		return
	}
}
